![alt text](image.png)


![alt text](image-1.png)

In [23]:
import numpy as np

In [24]:
def step(x):
    if x>=0:
        return 1
    return 0

In [25]:
# def perceptron(x,w):
#     t = x*w
#     t = sum(t)
#     return step(t)

def perceptron(x,w):
    x_new = x.reshape(1,-1)
    w_new = w.reshape(-1,1)
    r = x_new.dot(w_new)
    return step(r)

![alt text](image-2.png)

In [26]:
def p_not(x):
    y = -1 * x + 0.5
    return step(y)

not

In [27]:
x = np.array([1,0])
w = np.array([0.5,-1])
perceptron(x,w)

1

and

In [28]:
x = np.array([1,1,1])
w = np.array([-1.5,1,1])
perceptron(x,w)

1

![alt text](image-3.png)

![alt text](image-4.png)


- Tenserflow -> teano(C++) -> Google -> معماریش فیکس و استاتیک -> برای صنعت بهتره
- Pytorch -> Torch -> Facebook -> معماریش داینامیک و میشه عوض کرد - برای کارای تحقیقاتی و اکادمیک
- Dlib -> C++
- Dynet -> C++
- Caffe - > C++
- mlpack -> C++

In [29]:
# ! pip install tensorflow
# ! pip install torch
# ! C:\ProgramData\anaconda3\python.exe -m pip install --upgrade pip

- CPU -> 8
  - xeon Gold -> 80
- GPU -> بدرد هوشمصنویی و هک پسورد و ... میخوره
  - Ti 1080 -> 3500
  - CUDA
- TPU

In [30]:
!nvidia-smi

Thu Jul 24 16:04:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.88                 Driver Version: 576.88         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 750 Ti    WDDM  |   00000000:01:00.0  On |                  N/A |
| 33%   40C    P0              3W /   46W |    1059MiB /   2048MiB |      6%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [31]:
import tensorflow as tf

In [32]:
tf.version

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Taha\\AppData\\Roaming\\Python\\Python312\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>

## تابع تحریک

جای step function

![alt text](image-5.png)

- میشه ازش احتمال رو به دست اورد
- 0.1 بین

![alt text](image-7.png)

- -1.1 بین
- سرعت بالاتری داره

![alt text](image-6.png)

- پراستفاده
- برای رگرسیون یا لایه میانی کاربرد داره

![alt text](image-8.png)

### Softmax

- یک ولیو پیوسته رو به یک تعداد ثابت از اعداد گسسته مپ کنه
- تابع توضیع احتمال
- برای مالتی کلس کلسیفر استفاده میشه

![alt text](image-9.png)

- باینری بودیم سیگموید 
- مالتی کلاس بودیم سافت مکس

In [33]:
from keras.models import Sequential # ساده فید فوروارد هر لایه میره تو لایه بعدی بعدش
# from keras.models import Functional # برای مدل های پیچیده که فیدبک داشته باشه
# from keras.models import Model # اگه بخایم یه شبکه عصبی کاملا فاکشنال درست کنیم 

In [34]:
from keras.layers import Dense # ساده ترین که همون پرسپترون هست
from keras.layers import Input # ورودی شبکه عصبی

In [35]:
# from keras.datasets import mnist # همون دیجیت ولی بزرگ تر

In [36]:
import numpy as np
import pandas as pd

In [54]:
df = pd.read_csv('./iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [55]:
x = df.drop(['Species','Id'], axis=1).values
y = df['Species'].values

In [56]:
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [57]:
encoder = LabelEncoder()
y_labeled = encoder.fit_transform(y)
y_labeled

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [58]:
encoder.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [59]:
y_one_hot = to_categorical(y_labeled)
y_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [60]:
import pickle  # از رم تو هارد ذخیره میکنه

In [61]:
with open('encoder.bin', 'wb') as f:
    pickle.dump(encoder, f)

In [71]:
model = Sequential()

model.add(Input(shape=(4,)))  # ورودی 4 تا نود داره
model.add(Dense(2, activation='relu'))  # لایه اول 2 تا نود داره و اکتیویشن رلو
model.add(Dense(3, activation='softmax'))  # لایه آخر 1 تا نود داره و اکتیویشن سافت مکس

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.compile('adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [74]:
model.fit(x, y_one_hot, epochs=300)

Epoch 1/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5420 - loss: 1.2398
Epoch 2/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5670 - loss: 1.2361 
Epoch 3/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5871 - loss: 1.2005 
Epoch 4/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5958 - loss: 1.1940 
Epoch 5/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5820 - loss: 1.2025 
Epoch 6/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6142 - loss: 1.1529
Epoch 7/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5948 - loss: 1.1983 
Epoch 8/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6131 - loss: 1.1699 
Epoch 9/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6027 - loss: 1.1585 
Epoch 10/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6191 - loss: 1.1270
Epoch 11/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6322 - loss: 1.1125 
Epoch 12/300
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6578 - lo

In [75]:
model.predict(np.array([[1,2,3,4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[0.00124289, 0.19895318, 0.7998039 ]], dtype=float32)