![alt text](image.png)


![alt text](image-1.png)

- فرق پرسپترون با دیپ اینه که پرسپترون فقط خطی حساب میکنه ولی اون یکی غیر خطی


In [232]:
import numpy as np

In [233]:
def step(x):
    if x>=0:
        return 1
    return 0

In [234]:
# def perceptron(x,w):
#     t = x*w
#     t = sum(t)
#     return step(t)

def perceptron(x,w):
    x_new = x.reshape(1,-1)
    w_new = w.reshape(-1,1)
    r = x_new.dot(w_new)
    return step(r)

![alt text](image-2.png)

In [235]:
def p_not(x):
    y = -1 * x + 0.5
    return step(y)

not

In [236]:
x = np.array([1,0])
w = np.array([0.5,-1])
perceptron(x,w)

1

and

In [237]:
x = np.array([1,1,1])
w = np.array([-1.5,1,1])
perceptron(x,w)

1

![alt text](image-3.png)

![alt text](image-4.png)


- Tenserflow -> teano(C++) -> Google -> معماریش فیکس و استاتیک -> برای صنعت بهتره
- Pytorch -> Torch -> Facebook -> معماریش داینامیک و میشه عوض کرد - برای کارای تحقیقاتی و اکادمیک
- Dlib -> C++
- Dynet -> C++
- Caffe - > C++
- mlpack -> C++

In [238]:
# ! pip install tensorflow
# ! pip install torch
# ! C:\ProgramData\anaconda3\python.exe -m pip install --upgrade pip

- CPU -> 8
  - xeon Gold -> 80
- GPU -> بدرد هوشمصنویی و هک پسورد و ... میخوره
  - Ti 1080 -> 3500
  - CUDA
- TPU

In [239]:
!nvidia-smi

Fri Jul 25 20:21:14 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.88                 Driver Version: 576.88         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 750 Ti    WDDM  |   00000000:01:00.0  On |                  N/A |
| 33%    0C    P0              4W /   46W |     846MiB /   2048MiB |      9%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [240]:
import tensorflow as tf

In [241]:
tf.version

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Taha\\AppData\\Roaming\\Python\\Python312\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>

## تابع تحریک

جای step function

![alt text](image-5.png)

- میشه ازش احتمال رو به دست اورد
- 0.1 بین

![alt text](image-7.png)

- -1.1 بین
- سرعت بالاتری داره

![alt text](image-6.png)

- پراستفاده
- برای رگرسیون یا لایه میانی کاربرد داره

![alt text](image-8.png)

### Softmax

- یک ولیو پیوسته رو به یک تعداد ثابت از اعداد گسسته مپ کنه
- تابع توضیع احتمال
- برای مالتی کلس کلسیفر استفاده میشه

![alt text](image-9.png)

- باینری بودیم سیگموید 
- مالتی کلاس بودیم سافت مکس

In [242]:
from keras.models import Sequential # ساده فید فوروارد هر لایه میره تو لایه بعدی بعدش
# from keras.models import Functional # برای مدل های پیچیده که فیدبک داشته باشه
# from keras.models import Model # اگه بخایم یه شبکه عصبی کاملا فاکشنال درست کنیم 

- شبکه عصبی یک لایه 99.99 درصد رو پیدا میکنه


In [243]:
from keras.layers import Dense # ساده ترین که همون پرسپترون هست
from keras.layers import Input # ورودی شبکه عصبی

In [244]:
# from keras.datasets import mnist # همون دیجیت ولی بزرگ تر

In [245]:
import numpy as np
import pandas as pd

import pickle  # از رم تو هارد ذخیره میکنه

In [246]:
df = pd.read_csv('./iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [247]:
x = df.drop(['Species','Id'], axis=1).values
y = df['Species'].values

In [248]:
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [249]:
encoder = LabelEncoder()
y_labeled = encoder.fit_transform(y)
y_labeled

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [250]:
with open('encoder.bin', 'wb') as f:
    pickle.dump(encoder, f)

In [251]:
encoder.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [252]:
y_one_hot = to_categorical(y_labeled)
y_one_hot

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

- Input =>توی ورودی به تعداد فیچر ها
- Dense => تو لایه اخر به تعداد کلاس ها
- لایه وسط بشه میانگین ورودی و خروجی

- اگه وسط خیلی زیاد شد میشه به توان 2 رند کرد که دلیل خاصی نداره مثلا اگه شد 17 ما 16 تا بزاریم

### Output : 
- Regression : Relu , Linear
- Binary Classification : Sigmoid
- MultiClass : Softmax

### Other :
- Relu , tanh




In [253]:
model = Sequential() #-> یعنی مودل فیت فوروارده

model.add(Input(shape=(4,)))  # ورودی 4 تا نود داره


# لایه اول
model.add(Dense(4, activation='relu'))  # لایه اول 2 تا نود داره و اکتیویشن رلو => 4+3/2

# لایه هیدن
model.add(Dense(3, activation='relu'))

# لایه اخر
model.add(Dense(3, activation='softmax'))  # لایه آخر 3 تا نود داره و اکتیویشن سافت مکس برای کلاسیفیکیشن
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │            15 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 3)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 47 (188.00 B)

 Trainable params: 47 (188.00 B)

 Non-trainable params: 0 (0.00 B)

### optimizer  
- adam -> جدید تره -> برای کلسیفیکیشن
- RMSprop -> برای رگریسون
- SGD -> دقت پاییت ولی سرعت بالا

### loss
- تابع هزینه که میگه از جواب چقدر فاصله داریم

- Regression : MSE
- Binary Classification : binary_crossentropy
- MultiClass : categorical_crossentropy

### metrics
- رگرسون بود نمیخاد بدیم 
- accuracy=>  کلسیفیکیشن بودیم میشه همون F1 score

In [254]:
model.compile('adam', loss='categorical_crossentropy', metrics=['accuracy'])

### epochs
- یه بار وزن هارو رندوم میده و از دیتای اول شروع میکنه تا اخر و با هر دیتا وزن هارو اپدیت میکنه که این کار رو میگن یک دونه اپوک
- دیتا های پایین تر تاثیر بیشتری میزارن و باید تعداد بالاتری بگیریم 
- هرچی تعداد اپوک بیشتر بشه فرایند اموزش بیشتر انجام میشه و به جواب نزدیک تر میشیم
- اگه رکورد ها زیاده یعنی به ازای هر کلاس بین 1000 تا 8000 که اپوک 10 تا 25 باشه اوکیه
- اگه دیتا کم باشه باید اپوک هارو زیاد کنیم مثلا 300 تا

### EarlyStopping = 500 
- میاد جایی که خوب باشه استاپ میکنه

### batch_size
- اگه بزاریم 100 میاد 100 تا 100 تا اپدیت میکنه که باعت افزایش سرعت میشه
- هرچی بزرگ تر باشه جلوگیری میکنه از اور فیت شذن و باعت تاثیر داده پرت کم میشه

### validation_split = 0.2
- میاد 20 درصد از دیتارو میزاره کنار تست میکنه 

### validation_data 
- اگه خودت دیتای تست گداشته بودی کنار از این استفاده میشه

In [255]:
model.fit(x, y_one_hot, epochs=30,validation_split=0.2 )

Epoch 1/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 107ms/step - accuracy: 0.4281 - loss: 1.0653 - val_accuracy: 0.0000e+00 - val_loss: 2.4692
Epoch 2/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4281 - loss: 1.0657 - val_accuracy: 0.0000e+00 - val_loss: 2.3624
Epoch 3/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4417 - loss: 0.9880 - val_accuracy: 0.0000e+00 - val_loss: 2.2689
Epoch 4/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.4052 - loss: 1.0541 - val_accuracy: 0.0000e+00 - val_loss: 2.1740
Epoch 5/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3875 - loss: 1.0637 - val_accuracy: 0.0000e+00 - val_loss: 2.0854
Epoch 6/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.4000 - loss: 1.0002 - val_accuracy: 0.0000e+00 - val_loss: 2.0056
Epoch 7/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.4000 - loss: 1.0130 - val_accuracy: 0.0000e+00 - val_loss: 1.9311
Epoch 8/30
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3792 - loss: 0.9526 - val_accurac

In [256]:
model.predict(np.array([[1,2,3,4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step


array([[0.3098265 , 0.34850433, 0.34166923]], dtype=float32)