In [1]:
import numpy as np

In [2]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [4]:

def spiral_matrix(n):
    mat = np.zeros((n, n), dtype=int)
    left, right, top, bottom = 0, n-1, 0, n-1
    num = 1
    
    while left <= right and top <= bottom:
        # حرکت به راست
        for i in range(left, right+1):
            mat[top, i] = num
            num += 1
        top += 1

        # حرکت به پایین
        for i in range(top, bottom+1):
            mat[i, right] = num
            num += 1
        right -= 1

        # حرکت به چپ
        for i in range(right, left-1, -1):
            mat[bottom, i] = num
            num += 1
        bottom -= 1

        # حرکت به بالا
        for i in range(bottom, top-1, -1):
            mat[i, left] = num
            num += 1
        left += 1

    return mat

print(spiral_matrix(5))

[[ 1  2  3  4  5]
 [16 17 18 19  6]
 [15 24 25 20  7]
 [14 23 22 21  8]
 [13 12 11 10  9]]


In [5]:
a = np.arange(1, 37).reshape(6, 6)
print(a)

# قطر اصلی
print("Main Diagonal:", np.diag(a))

# قطر فرعی
print("Anti Diagonal:", np.diag(np.fliplr(a)))

# چهار بلوک
print("Top-left block:\n", a[:3, :3])
print("Top-right block:\n", a[:3, 3:])
print("Bottom-left block:\n", a[3:, :3])
print("Bottom-right block:\n", a[3:, 3:])




[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Main Diagonal: [ 1  8 15 22 29 36]
Anti Diagonal: [ 6 11 16 21 26 31]
Top-left block:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Top-right block:
 [[ 4  5  6]
 [10 11 12]
 [16 17 18]]
Bottom-left block:
 [[19 20 21]
 [25 26 27]
 [31 32 33]]
Bottom-right block:
 [[22 23 24]
 [28 29 30]
 [34 35 36]]


In [6]:
a = np.random.randint(0, 100, (100))

# 5 تا بزرگترین
print("Top 5:", np.sort(a)[-5:])

# 5 تا کوچکترین
print("Bottom 5:", np.sort(a)[:5])

# میانه
print("Median:", np.median(a))

# چارک‌ها
print("25%:", np.percentile(a, 25))
print("50%:", np.percentile(a, 50))  # همون Median
print("75%:", np.percentile(a, 75))


Top 5: [96 97 97 97 99]
Bottom 5: [0 1 1 1 1]
Median: 39.0
25%: 20.0
50%: 39.0
75%: 75.0


In [7]:
A = np.random.randint(1, 10, (4, 6))
print("A:\n", A)

AT = A.T
print("Transpose:\n", AT)

# ضرب ماتریسی A * A^T
M = A @ AT
print("A @ A.T:\n", M)

# بررسی متقارن بودن
print("Is symmetric?", np.allclose(M, M.T))


A:
 [[3 5 9 4 9 4]
 [6 7 8 3 7 7]
 [9 5 5 2 9 4]
 [1 9 7 2 6 9]]
Transpose:
 [[3 6 9 1]
 [5 7 5 9]
 [9 8 5 7]
 [4 3 2 2]
 [9 7 9 6]
 [4 7 4 9]]
A @ A.T:
 [[228 228 202 209]
 [228 256 226 236]
 [202 226 232 183]
 [209 236 183 252]]
Is symmetric? True


In [8]:
image = np.random.randint(0, 10, (5, 5))
kernel = np.array([[1,0,-1],
                   [1,0,-1],
                   [1,0,-1]])

# خروجی 3x3 چون (5-3+1)x(5-3+1)
out = np.zeros((3, 3), dtype=int)

for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]   # برش 3x3
        out[i, j] = np.sum(region * kernel)

print("Image:\n", image)
print("Kernel:\n", kernel)
print("Convolution Result:\n", out)


Image:
 [[3 8 0 2 0]
 [5 9 1 9 4]
 [7 4 1 3 4]
 [3 7 5 3 5]
 [6 1 5 0 7]]
Kernel:
 [[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]
Convolution Result:
 [[13  7 -6]
 [ 8  5 -6]
 [ 5  6 -5]]


In [9]:
x = np.array([1,2,3,4,5]).reshape(1,5)
y = np.array([1,2,3,4,5]).reshape(5,1)

print("Outer product:\n", x * y)


Outer product:
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [10]:
A = np.random.randint(1, 10, (3, 3))
vals, vecs = np.linalg.eig(A)

print("Matrix:\n", A)
print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)


Matrix:
 [[9 9 7]
 [3 7 2]
 [5 6 4]]
Eigenvalues: [16.88582232  0.13935237  2.97482532]
Eigenvectors:
 [[-0.81128999 -0.66248954  0.73593818]
 [-0.34211248  0.07234442 -0.64723324]
 [-0.47409662  0.74556951  0.19870615]]


In [11]:
def check_sudoku(board):
    for i in range(9):
        row = board[i, :]
        col = board[:, i]
        if len(np.unique(row)) != 9 or len(np.unique(col)) != 9:
            return False
    return True

# نمونه تست (سودوکو معتبر)
board = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

print("Sudoku valid?", check_sudoku(board))


Sudoku valid? True
