In [85]:
import numpy as np

In [86]:

a = np.array([1,2,3,4])

In [87]:
a

array([1, 2, 3, 4])

In [88]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
print(a.shape,b.shape)

(4,) (2, 3)


In [90]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [91]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [92]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [93]:
a.resize((2,2))    # این میاد خودش رو ریشیپ میکنه و در داده ریاد به درد میخوره


In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [95]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [96]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a*b
c

array([ 4, 10, 18])

In [97]:
# broadcasting
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c= a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [98]:
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
c= b.dot(a)     # ضرب ماتریکسی
c


array([32])

In [99]:
c = np.array((10))
d = a + c
d

array([[11],
       [12],
       [13]])

In [100]:
e = a + 10
e

array([[11],
       [12],
       [13]])

In [101]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [102]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [103]:
a = np.array([[1, 2, 3,4],[5, 7, 8, 9]])

In [104]:
# axis 0 باشه همه رو با هم جمع میکنه و برای جمع ابعاد
num_a = np.sum(a,axis=1)  
num_a

array([10, 29])

In [105]:
max_a = np.max(a)
max_a

np.int64(9)

In [106]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [107]:
a = np.random.randint(-10,10,(3,4))
a

array([[-10,  -9,   1,   5],
       [ -4,   4, -10,   5],
       [  8,  -8,  -2,  -9]], dtype=int32)

In [108]:
# پرفورمنسی خوب نیست
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack( (a,b) )
c


array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
c.shape

(2, 3)

In [110]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [111]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [112]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [113]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [114]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [115]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [116]:
np.mean(norm_a)

np.float64(0.0)

In [117]:
np.std(norm_a)

np.float64(1.0)

# new

In [118]:
a = np.array([[1,2,3],[4,5,6]])

In [119]:
a.shape

(2, 3)

In [120]:
a.ndim

2

 تعداد بایت ها

In [121]:
a.itemsize  

8

 تعداد کل چیز های شیپ که ضرب شده

In [122]:
a.size  

6

 مقدار رم اشغالی

In [123]:
a.size *a.itemsize  

48

dtype

In [124]:
a.dtype

dtype('int64')

In [125]:
f = np.array([1],dtype = 'uint8')
f.dtype

dtype('uint8')

In [126]:
1000 *  1024*768*8  / (1024**2)   # uint64هزازتا عکس 6 گیگ رم رو پر میکنه اگه 
1000 *  1024*768*1  / (1024**2)   # uint8هزازتا عکس 750 مگ رم رو پر میکنه اگه 

750.0

uint8 از 0 تا 255    <br>
int8 از -127 تا +128

اگه چیزی صفر داخل نباشه

In [127]:
a.all()  

np.True_

In [128]:
q = np.array([[0,2,3],[4,5,6]])
q.all()  

np.False_

generate

In [129]:
np.arange(3,20,3, dtype='uint8')

array([ 3,  6,  9, 12, 15, 18], dtype=uint8)

In [130]:
np.linspace(0,10,50,retstep=True)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 np.float64(0.20408163265306123))

In [131]:
np.zeros((4,3),dtype='uint8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [132]:
np.ones((4,3),dtype='uint8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [133]:
np.full((4,3),20,dtype='uint8')

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]], dtype=uint8)

In [134]:
np.diag([1,2,3,4,5,6],k=1)

array([[0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0]])

In [135]:
import random

nums = []

for i in range(100000):
    nums.append(random.randint(1, 100))

In [136]:
count = {}

for i in nums:
    if i in count:
        count[i]+=1
    else:
        count[i] = i

In [137]:
count

{31: 1051,
 90: 1067,
 47: 1015,
 73: 1101,
 60: 1034,
 76: 1082,
 82: 1038,
 85: 1097,
 51: 1061,
 28: 1013,
 37: 1049,
 9: 1034,
 6: 1015,
 77: 1076,
 63: 1015,
 29: 1072,
 98: 1113,
 62: 1032,
 56: 999,
 96: 1093,
 10: 1041,
 22: 1049,
 89: 1070,
 61: 1080,
 38: 1075,
 94: 1132,
 18: 986,
 3: 929,
 93: 1073,
 55: 1072,
 17: 997,
 24: 994,
 41: 1031,
 87: 1091,
 80: 1054,
 67: 1070,
 20: 1010,
 66: 1150,
 64: 1085,
 88: 1035,
 25: 997,
 45: 1023,
 13: 1037,
 74: 1029,
 59: 1089,
 30: 1048,
 83: 1074,
 35: 1057,
 46: 1021,
 78: 1057,
 32: 1085,
 36: 1030,
 57: 1092,
 52: 1063,
 54: 1057,
 39: 1064,
 14: 1011,
 44: 1071,
 43: 1048,
 40: 1080,
 100: 1135,
 92: 1106,
 84: 1042,
 86: 1048,
 26: 946,
 95: 1070,
 50: 1009,
 72: 1118,
 81: 1052,
 79: 1034,
 42: 1036,
 69: 1054,
 53: 1135,
 34: 1036,
 23: 1088,
 99: 1091,
 7: 1032,
 70: 1018,
 5: 1052,
 21: 1065,
 33: 1073,
 12: 976,
 27: 992,
 48: 1018,
 97: 1143,
 2: 1016,
 4: 988,
 58: 1014,
 15: 1021,
 1: 963,
 16: 952,
 91: 1085,
 71: 11

In [138]:
np.random.uniform(1,100,(10,))

array([65.46385151, 92.7279465 , 35.21572869, 71.70478668, 61.14336768,
       90.43580156, 80.17837978, 94.00878067, 33.22684646, 26.01768862])

In [139]:
np.random.uniform(size=(3,4))

array([[0.19754287, 0.51224378, 0.14786607, 0.11949509],
       [0.03163282, 0.05387934, 0.1338619 , 0.85199908],
       [0.8608758 , 0.47596834, 0.79200169, 0.82748479]])

In [140]:
np.random.normal(size=(3,4))

array([[-0.60798216,  0.67371624,  1.3344793 ,  0.62194808],
       [-1.95709128, -0.12828722, -1.52522743, -0.45915029],
       [ 0.74078614,  1.23825831,  1.48467782,  0.18288163]])

In [141]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.zeros((4,3),dtype='uint8')


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [142]:
a= np.arange(1,26).reshape(5,-1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [143]:
a[3][1]   # incorrect  چون رم زیاد مصرف میکنه و کنده

np.int64(17)

In [144]:
a[3,1]  

np.int64(17)

In [145]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

# advanced subscription

In [146]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [147]:
a[[0,2],[3,1]]  # (0,3) (2,1)

array([ 4, 12])

In [148]:
a[[0,2],1:4]  

array([[ 2,  3,  4],
       [12, 13, 14]])

In [149]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
a>50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [151]:
x = np.random.randint(0,100,(5,5))
x

array([[ 9, 83, 61, 73, 24],
       [68, 79, 35, 96,  6],
       [84, 14, 27, 53, 69],
       [95, 73,  1,  1, 60],
       [ 4,  8, 65, 29, 92]], dtype=int32)

In [152]:
x>50

array([[False,  True,  True,  True, False],
       [ True,  True, False,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [False, False,  True, False,  True]])

In [153]:
c = x>50
x[c]

array([83, 61, 73, 68, 79, 96, 84, 53, 69, 95, 73, 60, 65, 92],
      dtype=int32)

In [154]:
x[x>50]

array([83, 61, 73, 68, 79, 96, 84, 53, 69, 95, 73, 60, 65, 92],
      dtype=int32)

In [155]:
filter = x>50

np.where(filter)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4]),
 array([1, 2, 3, 0, 1, 3, 0, 3, 4, 0, 1, 4, 2, 4]))

In [156]:
f1 = x>50
f2 = x<70

# f1 and f2    #incorrect
f = f1 & f2
np.where(f)

(array([0, 1, 2, 2, 3, 4]), array([2, 0, 3, 4, 4, 2]))

In [157]:
f1 = x>50
f2 = x<70

# f1 or f2    #incorrect
f = f1 | f2
np.where(f)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4]))

In [158]:
# x>50 | x<70 #incorrect
(x>50) | (x<70)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [159]:
users = np.array(['ali','maryam','taha','jafar'])
ranks = np.array([-1,1,0.5,2])

users[ranks>0]

array(['maryam', 'taha', 'jafar'], dtype='<U6')

In [160]:
m = np.max(ranks)
# f = (ranks==m)
f = (np.isclose(ranks,m))
users[f]

array(['jafar'], dtype='<U6')

In [161]:
np.argmax(ranks)

np.int64(3)

In [162]:
users[np.argmax(ranks)]

np.str_('jafar')

In [ ]:
np.argsort(ranks) # کم به زیاد

array([0, 2, 1, 3])

In [168]:
ranks[np.argsort(ranks)]

array([-1. ,  0.5,  1. ,  2. ])

In [169]:
users[np.argsort(ranks)]

array(['ali', 'taha', 'maryam', 'jafar'], dtype='<U6')

In [174]:
np.argsort(ranks)[::-1] 

array([3, 1, 2, 0])

In [175]:
users[np.argsort(ranks)[::-1] ]

array(['jafar', 'maryam', 'taha', 'ali'], dtype='<U6')

# Floating point error (IEEE 756)
### UNSIGEND INT
```
1 Byte = 8 bit -> 256 ->  0 - 256
                            -128 - +127

2 Byte = 16 bit -> 65536 ->  0 - 65535
                            -32768 - +32767
```


$23_{10} = {00010111}_2$


### SIGEND INT
### Sing Bit
```
+23 = [00010111]
-23 = [10010111]  Sing Bit
```

In [164]:
np.floor(np.log10(326456))+1  # تعداد عدد


np.float64(6.0)

In [165]:
a = f'{2113:b}'
print(a)

100001000001


In [166]:
# باگ اصلی بخاطر خطی اعشار
print(0.1 + 0.2)
0.1 + 0.2 == 0.3


0.30000000000000004


False

# isclose

In [167]:
np.isclose(0.1 + 0.2 , 0.3)

np.True_

# add pading

In [176]:
x = np.random.randint(0,100,(5,5))
x

array([[79, 91, 53, 28, 91],
       [ 1, 75, 36, 40, 55],
       [99,  3, 10, 23, 49],
       [41, 46, 50, 75, 53],
       [93, 32, 97, 90, 85]], dtype=int32)

In [181]:
z = np.zeros((7,7))
z[1:-1,1:-1] = x
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 79., 91., 53., 28., 91.,  0.],
       [ 0.,  1., 75., 36., 40., 55.,  0.],
       [ 0., 99.,  3., 10., 23., 49.,  0.],
       [ 0., 41., 46., 50., 75., 53.,  0.],
       [ 0., 93., 32., 97., 90., 85.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [182]:
np.pad(x,1)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 79, 91, 53, 28, 91,  0],
       [ 0,  1, 75, 36, 40, 55,  0],
       [ 0, 99,  3, 10, 23, 49,  0],
       [ 0, 41, 46, 50, 75, 53,  0],
       [ 0, 93, 32, 97, 90, 85,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [187]:
np.pad(x,((1,1),(2,2)))

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 79, 91, 53, 28, 91,  0,  0],
       [ 0,  0,  1, 75, 36, 40, 55,  0,  0],
       [ 0,  0, 99,  3, 10, 23, 49,  0,  0],
       [ 0,  0, 41, 46, 50, 75, 53,  0,  0],
       [ 0,  0, 93, 32, 97, 90, 85,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [193]:
x = np.arange(0,20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])