In [15]:
import numpy as np

In [16]:

a = np.array([1,2,3,4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
print(a.shape,b.shape)

(4,) (2, 3)


In [20]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [21]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [22]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [25]:
c = np.array((10))
d = a + c
d

array([11, 12, 13])

In [26]:
e = a + 10
e

array([11, 12, 13])

In [27]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [28]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [29]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
num_a = np.sum(a)
num_a

np.int64(45)

In [31]:
max_a = np.max(a)
max_a

np.int64(9)

In [32]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [33]:
a = np.random.randint(-10,10,(3,4))
a

array([[-1,  1,  4,  7],
       [ 1,  8,  9, -4],
       [ 0, -4, -1, -7]], dtype=int32)

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
c


array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
c.shape

(2, 3)

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [37]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [38]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [39]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [40]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [41]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [42]:
np.mean(norm_a)

np.float64(0.0)

In [43]:
np.std(norm_a)

np.float64(1.0)