In [1]:
import numpy as np

In [2]:

a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(a.shape,b.shape)

(4,) (2, 3)


In [6]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [7]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [8]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [9]:
a.resize((2,2))    # این میاد خودش رو ریشیپ میکنه و در داده ریاد به درد میخوره


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a*b
c

array([ 4, 10, 18])

In [13]:
# broadcasting
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c= a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [14]:
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
c= b.dot(a)     # ضرب ماتریکسی
c


array([32])

In [15]:
c = np.array((10))
d = a + c
d

array([[11],
       [12],
       [13]])

In [16]:
e = a + 10
e

array([[11],
       [12],
       [13]])

In [17]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [18]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [19]:
a = np.array([[1, 2, 3,4],[5, 7, 8, 9]])

In [20]:
# axis 0 باشه همه رو با هم جمع میکنه و برای جمع ابعاد
num_a = np.sum(a,axis=1)  
num_a

array([10, 29])

In [21]:
max_a = np.max(a)
max_a

np.int64(9)

In [22]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [23]:
a = np.random.randint(-10,10,(3,4))
a

array([[  1,  -4,  -4,   8],
       [ -5, -10,   0,  -6],
       [ -4,  -5,  -9,   7]], dtype=int32)

In [24]:
# پرفورمنسی خوب نیست
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack( (a,b) )
c


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
c.shape

(2, 3)

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [27]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [28]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [29]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [30]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [31]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [32]:
np.mean(norm_a)

np.float64(0.0)

In [33]:
np.std(norm_a)

np.float64(1.0)

# new

In [34]:
a = np.array([[1,2,3],[4,5,6]])

In [35]:
a.shape

(2, 3)

In [36]:
a.ndim

2

 تعداد بایت ها

In [37]:
a.itemsize  

8

 تعداد کل چیز های شیپ که ضرب شده

In [38]:
a.size  

6

 مقدار رم اشغالی

In [39]:
a.size *a.itemsize  

48

dtype

In [40]:
a.dtype

dtype('int64')

In [41]:
f = np.array([1],dtype = 'uint8')
f.dtype

dtype('uint8')

In [42]:
1000 *  1024*768*8  / (1024**2)   # uint64هزازتا عکس 6 گیگ رم رو پر میکنه اگه 
1000 *  1024*768*1  / (1024**2)   # uint8هزازتا عکس 750 مگ رم رو پر میکنه اگه 

750.0

uint8 از 0 تا 255    <br>
int8 از -127 تا +128

اگه چیزی صفر داخل نباشه

In [43]:
a.all()  

np.True_

In [44]:
q = np.array([[0,2,3],[4,5,6]])
q.all()  

np.False_

generate

In [45]:
np.arange(3,20,3, dtype='uint8')

array([ 3,  6,  9, 12, 15, 18], dtype=uint8)

In [46]:
np.linspace(0,10,50,retstep=True)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 np.float64(0.20408163265306123))

In [47]:
np.zeros((4,3),dtype='uint8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [48]:
np.ones((4,3),dtype='uint8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [49]:
np.full((4,3),20,dtype='uint8')

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]], dtype=uint8)

In [50]:
np.diag([1,2,3,4,5,6],k=1)

array([[0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0]])

In [51]:
import random

nums = []

for i in range(100000):
    nums.append(random.randint(1, 100))

In [52]:
count = {}

for i in nums:
    if i in count:
        count[i]+=1
    else:
        count[i] = i

In [53]:
count

{90: 1063,
 30: 1089,
 69: 1071,
 73: 1138,
 64: 1080,
 34: 1060,
 17: 968,
 87: 1082,
 2: 1009,
 18: 1031,
 44: 1063,
 78: 1090,
 59: 1029,
 27: 1016,
 53: 1087,
 13: 1043,
 42: 1059,
 35: 1028,
 70: 1079,
 45: 1057,
 47: 1037,
 86: 1070,
 29: 1060,
 28: 1058,
 48: 1015,
 15: 986,
 96: 1136,
 21: 1006,
 60: 1066,
 16: 1039,
 67: 1055,
 61: 1020,
 24: 1026,
 20: 1067,
 49: 1043,
 10: 1033,
 41: 1048,
 62: 1006,
 38: 1003,
 11: 986,
 12: 942,
 84: 1063,
 23: 1008,
 43: 1030,
 92: 1089,
 40: 999,
 37: 1022,
 9: 1026,
 100: 1119,
 95: 1105,
 32: 1035,
 5: 1021,
 25: 1007,
 52: 1026,
 46: 1080,
 1: 981,
 91: 1115,
 97: 1172,
 54: 1080,
 74: 1118,
 89: 1073,
 8: 986,
 14: 1068,
 65: 1029,
 99: 1129,
 6: 1007,
 94: 1078,
 55: 1043,
 66: 1092,
 57: 1068,
 33: 1024,
 50: 1080,
 93: 1063,
 71: 1021,
 51: 1028,
 82: 1051,
 4: 1027,
 88: 1073,
 79: 1085,
 85: 1102,
 80: 1095,
 68: 1033,
 56: 1010,
 22: 1079,
 98: 1083,
 77: 1151,
 83: 1028,
 36: 1051,
 39: 1097,
 19: 959,
 7: 991,
 31: 992,
 63: 

In [54]:
np.random.uniform(1,100,(10,))

array([59.8339636 , 27.96351694, 16.27340116, 73.92641923, 48.28865375,
       29.63683556, 81.06792283, 75.47806808, 56.89478188, 75.05010358])

In [55]:
np.random.uniform(size=(3,4))

array([[0.35861088, 0.88686032, 0.98132359, 0.02335847],
       [0.6760259 , 0.20991819, 0.80076237, 0.74906301],
       [0.60076089, 0.68718325, 0.63134728, 0.36071666]])

In [56]:
np.random.normal(size=(3,4))

array([[ 1.68281667, -0.4573027 ,  0.41246304, -0.80884186],
       [ 1.024234  ,  0.66769464,  0.22883253, -0.70839594],
       [-0.7147274 , -0.55012626,  0.17592128,  1.51563832]])

In [57]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.zeros((4,3),dtype='uint8')


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [62]:
a= np.arange(1,26).reshape(5,-1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
a[3][1]   # incorrect  چون رم زیاد مصرف میکنه و کنده

np.int64(17)

In [64]:
a[3,1]  

np.int64(17)

In [65]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

# advanced subscription

In [67]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [69]:
a[[0,2],[3,1]]  # (0,3) (2,1)

array([ 4, 12])

In [72]:
a[[0,2],1:4]  

array([[ 2,  3,  4],
       [12, 13, 14]])

In [73]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
a>50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [76]:
x = np.random.randint(0,100,(5,5))
x

array([[38, 75, 15, 65, 62],
       [50, 50, 77,  6, 60],
       [21, 51, 32, 83,  8],
       [40, 79, 87, 90, 81],
       [99, 79, 37, 47, 45]], dtype=int32)

In [77]:
x>50

array([[False,  True, False,  True,  True],
       [False, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [80]:
c = x>50
x[c]

array([75, 65, 62, 77, 60, 51, 83, 79, 87, 90, 81, 99, 79], dtype=int32)