In [65]:
import numpy as np

In [66]:

a = np.array([1,2,3,4])

In [67]:
a

array([1, 2, 3, 4])

In [68]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
print(a.shape,b.shape)

(4,) (2, 3)


In [70]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [71]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [72]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [73]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [74]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [112]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a*b
c

array([ 4, 10, 18])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a.dot(b)     # ضرب ماتریکسی
c

np.int64(32)

In [75]:
c = np.array((10))
d = a + c
d

array([11, 12, 13])

In [76]:
e = a + 10
e

array([11, 12, 13])

In [77]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [78]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [79]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
num_a = np.sum(a)
num_a

np.int64(45)

In [81]:
max_a = np.max(a)
max_a

np.int64(9)

In [82]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [83]:
a = np.random.randint(-10,10,(3,4))
a

array([[ 1, -8, -9,  2],
       [-7,  5,  0,  0],
       [-9,  4,  2,  5]], dtype=int32)

In [84]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
c


array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
c.shape

(2, 3)

In [86]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [87]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [88]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [89]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [90]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [91]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [92]:
np.mean(norm_a)

np.float64(0.0)

In [93]:
np.std(norm_a)

np.float64(1.0)

# new

In [94]:
a = np.array([[1,2,3],[4,5,6]])

In [95]:
a.shape

(2, 3)

In [96]:
a.ndim

2

 تعداد بایت ها

In [97]:
a.itemsize  

8

 تعداد کل چیز های شیپ که ضرب شده

In [98]:
a.size  

6

 مقدار رم اشغالی

In [99]:
a.size *a.itemsize  

48

dtype

In [100]:
a.dtype

dtype('int64')

In [101]:
f = np.array([1],dtype = 'uint8')
f.dtype

dtype('uint8')

In [102]:
1000 *  1024*768*8  / (1024**2)   # uint64هزازتا عکس 6 گیگ رم رو پر میکنه اگه 
1000 *  1024*768*1  / (1024**2)   # uint8هزازتا عکس 750 مگ رم رو پر میکنه اگه 

750.0

uint8 از 0 تا 255    <br>
int8 از -127 تا +128

اگه چیزی صفر داخل نباشه

In [103]:
a.all()  

np.True_

In [104]:
q = np.array([[0,2,3],[4,5,6]])
q.all()  

np.False_

generate

In [111]:
np.arange(3,20,3, dtype='uint8')

array([ 3,  6,  9, 12, 15, 18], dtype=uint8)