In [13]:
import numpy as np

In [14]:
a = np.arange(1,5)
b = np.arange(5,9)
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [15]:
c  = np.stack((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
c  = np.stack((a,b),axis=1)
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [17]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]))

In [19]:
c  = np.stack((a,b))
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [21]:
c.shape

(2, 3, 3)

In [22]:
c  = np.stack((a,b),axis=1)
c

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [17, 18, 19]]])

In [23]:
c.shape

(3, 2, 3)

In [24]:
c  = np.stack((a,b),axis=2)
c

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

In [25]:
c.shape

(3, 3, 2)