In [1]:
import numpy as np

In [2]:

a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(a.shape,b.shape)

(4,) (2, 3)


In [6]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [7]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [8]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [ ]:
a.resize((2,-1,1))    # این میاد خودش رو ریشیپ میکنه و در داده ریاد به درد میخوره


In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a*b
c

array([ 4, 10, 18])

In [67]:
# broadcasting
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c= a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
c= b.dot(a)     # ضرب ماتریکسی
c


[[4]
 [5]
 [6]]
[[4]
 [5]
 [6]]


array([32])

In [13]:
c = np.array((10))
d = a + c
d

array([11, 12, 13])

In [14]:
e = a + 10
e

array([11, 12, 13])

In [15]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [16]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [17]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
num_a = np.sum(a)
num_a

np.int64(45)

In [19]:
max_a = np.max(a)
max_a

np.int64(9)

In [20]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [21]:
a = np.random.randint(-10,10,(3,4))
a

array([[ 9, -7, -7, -9],
       [ 6, -1,  9,  2],
       [ 3, -6,  8, -9]], dtype=int32)

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
c


array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c.shape

(2, 3)

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [25]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [26]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [27]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [28]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [29]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [30]:
np.mean(norm_a)

np.float64(0.0)

In [31]:
np.std(norm_a)

np.float64(1.0)

# new

In [32]:
a = np.array([[1,2,3],[4,5,6]])

In [33]:
a.shape

(2, 3)

In [34]:
a.ndim

2

 تعداد بایت ها

In [35]:
a.itemsize  

8

 تعداد کل چیز های شیپ که ضرب شده

In [36]:
a.size  

6

 مقدار رم اشغالی

In [37]:
a.size *a.itemsize  

48

dtype

In [38]:
a.dtype

dtype('int64')

In [39]:
f = np.array([1],dtype = 'uint8')
f.dtype

dtype('uint8')

In [40]:
1000 *  1024*768*8  / (1024**2)   # uint64هزازتا عکس 6 گیگ رم رو پر میکنه اگه 
1000 *  1024*768*1  / (1024**2)   # uint8هزازتا عکس 750 مگ رم رو پر میکنه اگه 

750.0

uint8 از 0 تا 255    <br>
int8 از -127 تا +128

اگه چیزی صفر داخل نباشه

In [41]:
a.all()  

np.True_

In [42]:
q = np.array([[0,2,3],[4,5,6]])
q.all()  

np.False_

generate

In [43]:
np.arange(3,20,3, dtype='uint8')

array([ 3,  6,  9, 12, 15, 18], dtype=uint8)

In [54]:
np.linspace(0,10,50,retstep=True)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 np.float64(0.20408163265306123))

In [57]:
np.zeros((4,3),dtype='uint8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [58]:
np.ones((4,3),dtype='uint8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [60]:
np.full((4,3),20,dtype='uint8')

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]], dtype=uint8)

In [63]:
np.diag([1,2,3,4,5,6],k=1)

array([[0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0]])