In [105]:
import numpy as np

In [106]:

a = np.array([1,2,3,4])

In [107]:
a

array([1, 2, 3, 4])

In [108]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
print(a.shape,b.shape)

(4,) (2, 3)


In [110]:
c = a.reshape((4,1))
c.shape

(4, 1)

In [111]:
d = a.reshape((2,2,1))
d.shape

(2, 2, 1)

In [112]:
dd = a.reshape((2,-1,1))
dd.shape   

(2, 2, 1)

In [113]:
a.resize((2,2))    # این میاد خودش رو ریشیپ میکنه و در داده ریاد به درد میخوره


In [114]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [115]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a+b
c

array([5, 7, 9])

In [116]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c= a*b
c

array([ 4, 10, 18])

In [117]:
# broadcasting
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
c= a*b
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [118]:
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
c= b.dot(a)     # ضرب ماتریکسی
c


array([32])

In [119]:
c = np.array((10))
d = a + c
d

array([[11],
       [12],
       [13]])

In [120]:
e = a + 10
e

array([[11],
       [12],
       [13]])

In [121]:
a = np.array([1, 2, 3,4, 5, 6, 7, 8, 9])
b = a[2:7:2]
b

array([3, 5, 7])

In [122]:
c = a[a>3]
c

array([4, 5, 6, 7, 8, 9])

In [123]:
a = np.array([[1, 2, 3,4],[5, 7, 8, 9]])

In [124]:
# axis 0 باشه همه رو با هم جمع میکنه و برای جمع ابعاد
num_a = np.sum(a,axis=1)  
num_a

array([10, 29])

In [125]:
max_a = np.max(a)
max_a

np.int64(9)

In [126]:
a = np.array([2,5,7,2,6,4,3,7,8])
b = np.sort(a)
b

array([2, 2, 3, 4, 5, 6, 7, 7, 8])

In [127]:
a = np.random.randint(-10,10,(3,4))
a

array([[-10,   6,   0,   8],
       [  5,   6,  -9,   6],
       [  8,  -7,   3,   5]], dtype=int32)

In [128]:
# پرفورمنسی خوب نیست
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack( (a,b) )
c


array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
c.shape

(2, 3)

In [130]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [131]:
a = np.array([1,2,3,4,5,6,7,8,9])


In [132]:
mean_a = np.mean(a)
mean_a

np.float64(5.0)

In [133]:
std_a = np.std(a) ## انحراف از معیار
std_a

np.float64(2.581988897471611)

In [134]:
std_a = np.std(a)
std_a

np.float64(2.581988897471611)

In [135]:
norm_a = (a-mean_a)/std_a  ## به سمت صفر بردن میانگین
norm_a

array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
        0.38729833,  0.77459667,  1.161895  ,  1.54919334])

In [136]:
np.mean(norm_a)

np.float64(0.0)

In [137]:
np.std(norm_a)

np.float64(1.0)

# new

In [138]:
a = np.array([[1,2,3],[4,5,6]])

In [139]:
a.shape

(2, 3)

In [140]:
a.ndim

2

 تعداد بایت ها

In [141]:
a.itemsize  

8

 تعداد کل چیز های شیپ که ضرب شده

In [142]:
a.size  

6

 مقدار رم اشغالی

In [143]:
a.size *a.itemsize  

48

dtype

In [144]:
a.dtype

dtype('int64')

In [145]:
f = np.array([1],dtype = 'uint8')
f.dtype

dtype('uint8')

In [146]:
1000 *  1024*768*8  / (1024**2)   # uint64هزازتا عکس 6 گیگ رم رو پر میکنه اگه 
1000 *  1024*768*1  / (1024**2)   # uint8هزازتا عکس 750 مگ رم رو پر میکنه اگه 

750.0

uint8 از 0 تا 255    <br>
int8 از -127 تا +128

اگه چیزی صفر داخل نباشه

In [147]:
a.all()  

np.True_

In [148]:
q = np.array([[0,2,3],[4,5,6]])
q.all()  

np.False_

generate

In [149]:
np.arange(3,20,3, dtype='uint8')

array([ 3,  6,  9, 12, 15, 18], dtype=uint8)

In [150]:
np.linspace(0,10,50,retstep=True)

(array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
         4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
         6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
         8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]),
 np.float64(0.20408163265306123))

In [151]:
np.zeros((4,3),dtype='uint8')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [152]:
np.ones((4,3),dtype='uint8')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [153]:
np.full((4,3),20,dtype='uint8')

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]], dtype=uint8)

In [154]:
np.diag([1,2,3,4,5,6],k=1)

array([[0, 1, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 0, 0, 0]])

In [155]:
import random

nums = []

for i in range(100000):
    nums.append(random.randint(1, 100))

In [156]:
count = {}

for i in nums:
    if i in count:
        count[i]+=1
    else:
        count[i] = i

In [157]:
count

{75: 1078,
 57: 1040,
 48: 1021,
 11: 1058,
 96: 1150,
 45: 1075,
 73: 1060,
 61: 1120,
 94: 1145,
 65: 1052,
 68: 1085,
 79: 1125,
 17: 1026,
 80: 1066,
 62: 1115,
 31: 1068,
 34: 1039,
 13: 985,
 71: 1140,
 90: 1129,
 82: 1042,
 42: 1028,
 93: 1084,
 91: 1124,
 6: 1006,
 37: 991,
 50: 1059,
 89: 1085,
 58: 1039,
 21: 1002,
 4: 1044,
 14: 1030,
 2: 977,
 83: 1061,
 1: 979,
 29: 1045,
 67: 998,
 97: 1135,
 53: 1101,
 9: 1013,
 84: 1056,
 15: 1019,
 23: 1004,
 81: 1044,
 26: 998,
 85: 1113,
 92: 1080,
 5: 1031,
 78: 1078,
 46: 1020,
 35: 1004,
 88: 1112,
 100: 1093,
 7: 975,
 36: 948,
 43: 994,
 54: 1087,
 18: 1007,
 24: 1025,
 27: 1084,
 69: 1021,
 70: 1072,
 25: 981,
 74: 1057,
 16: 985,
 72: 1063,
 38: 1029,
 51: 998,
 99: 1081,
 20: 1015,
 76: 1123,
 3: 953,
 56: 1063,
 40: 1015,
 8: 914,
 19: 1037,
 59: 1016,
 41: 1091,
 10: 992,
 95: 1171,
 47: 1058,
 77: 1100,
 98: 1116,
 22: 1034,
 39: 1047,
 28: 1044,
 30: 1026,
 44: 1028,
 33: 1046,
 66: 1079,
 60: 1034,
 86: 1064,
 12: 1051,


In [158]:
np.random.uniform(1,100,(10,))

array([12.10896112,  2.96378122,  6.9687235 , 81.97318092, 13.44095594,
       68.92147603, 58.80868248, 11.77858567, 34.2130521 , 49.89823861])

In [159]:
np.random.uniform(size=(3,4))

array([[0.54244282, 0.68062938, 0.57418007, 0.88173086],
       [0.05825705, 0.15106516, 0.22249949, 0.88461269],
       [0.59874742, 0.11270889, 0.31837374, 0.7182223 ]])

In [160]:
np.random.normal(size=(3,4))

array([[ 0.98036816,  0.56672265,  0.00552108, -0.15625012],
       [ 2.5581957 , -0.59861948, -0.3685159 ,  0.14992227],
       [-0.60111983,  1.15858258, -0.44113853, -1.62971983]])

In [162]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

np.zeros((4,3),dtype='uint8')


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [166]:
a= np.arange(1,22).reshape(-1,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a[3][1]   # incorrect  چون رم زیاد مصرف میکنه و کنده

np.int64(11)

In [171]:
a[3,1]  

np.int64(11)

In [172]:
a[::2]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])